### ISSUE TITLE
Compatibility with Typescript

### ISSUE THREAD

**Issue by jmbl1685** [aichbauer/node-convert-array-to-csv#13]
![image](https://user-images.githubusercontent.com/22874642/53740668-b66fad00-3e62-11e9-8a13-9c890772dce7.png)

This module is not yet compatible with Typescript.

Regards.

**Comment by aichbauer** [comment]
Hey @jmbl1685,

thanks for reaching out. I must say I barely touched TypeScript, so it would be hard for myself to add the support. As far as I know we have two options to achieve this result adding a type definition file to the package (which would be preferred if we rewrite the package in typescript), or publish a type definition to the @types organization on npm. 

Do you have experience in writing type definition files? Do you have further information of how we could achieve the typescript support?

**Comment by jmbl1685** [comment]
When I take a space I'll check to see if I can collaborate with the project. 

Thanks @aichbauer  with yor answer

**Comment by Qiming-Liu** [comment]
Thanks for the awesome code.
I added type definition to this.  :)  

PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61079
NPM https://www.npmjs.com/package/@types/convert-array-to-csv
