### ISSUE TITLE
Property with a value of 0 (zero) is written as empty string

### ISSUE THREAD

**Issue by dalbani** [aichbauer/node-convert-array-to-csv#18]
Contrary to the correct implementation of `convertArrayOfArraysToCSV` in https://github.com/aichbauer/node-convert-array-to-csv/blob/master/src/modules/convert-array-of-arrays-to-csv.js#L17, the one for `convertArrayOfObjectsToCSV` in https://github.com/aichbauer/node-convert-array-to-csv/blob/master/src/modules/convert-array-of-objects-to-csv.js#L26 uses a `||` falsy check and thus doesn't handle properties with a value of `0` properly.
Those are turned into an empty string (`""`) in the CSV output.

**Comment by aichbauer** [comment]
@dalbani you are right... I will fix it as soon as possible
