### ISSUE TITLE
Error generating csv file when last row and last column have space character

### ISSUE THREAD

**Issue by romeroleonardoalexandre** [aichbauer/node-convert-array-to-csv#20]
Hi, I'm using your library a lot, but when I want to generate a file, if the last row and last column there is a "space" character, then the file occurs a bug, which transforms the last column of the wrong last row and put a range (\ n) before the last quotation mark.
[example.txt](https://github.com/aichbauer/node-convert-array-to-csv/files/3443554/example.txt)

**Comment by aichbauer** [comment]
@romeroleonardoalexandre thanks for using this library 😀

I will work on this as soon as possible...

Could you provide me with some more details?

* Which version of this library are you using?
* Can you show me the code you are using?
* Can you show me the data you are using to generate the csv?
* Can you show me the malformed csv?
* Can you show me the desired csv output?

**Comment by romeroleonardoalexandre** [comment]
Version: 
`"convert-array-to-csv": "^1.0.5"`

Object to convert:
`let dados = {"rows":[{"btet_nnum":"9031828719046","btet_titi":"2","btet_titd":"Mensalidade EAD","btet_ticl":"M","btet_tcld":"Mensalidade","btet_pess":"1828719","btet_npar":"4","btet_conv":"40996","btet_nome":"Josely Braga Mesquita","btet_ende":"VILA TEIXEIRA","btet_bair":"CACIMBAS","btet_cida":"ITAPIPOCA","btet_ufpa":"CE","btet_cepp":"62502564","btet_dven":"2019-07-29 00:00:00","btet_code":"4","btet_valo":"132,04","btet_mult":null,"btet_qtdm":"0","btet_juro":null,"btet_djur":null,"btet_tdes":"0","btet_vdes":null,"btet_ddes":"2019-07-01 00:00:00","btet_vaba":null,"btet_tpro":"0","btet_qtdp":"0","btet_qtdb":"0","btet_mens":null,"btet_viof":null,"rebt_stat":"Não enviado"},{"btet_nnum":"9031918173077","btet_titi":"2","btet_titd":"Mensalidade EAD","btet_ticl":"M","btet_tcld":"Mensalidade","btet_pess":"1918173","btet_npar":"7","btet_conv":"40996","btet_nome":"Edilene Pereira Santos","btet_ende":"RUA DAVID NASSER","btet_bair":"PLANALTO","btet_cida":"BELO HORIZONTE","btet_ufpa":"MG","btet_cepp":"31720350","btet_dven":"2019-07-29 00:00:00","btet_code":"4","btet_valo":"305,26","btet_mult":null,"btet_qtdm":"0","btet_juro":null,"btet_djur":null,"btet_tdes":"0","btet_vdes":null,"btet_ddes":"2019-07-02 00:00:00","btet_vaba":null,"btet_tpro":"0","btet_qtdp":"0","btet_qtdb":"0","btet_mens":null,"btet_viof":null,"rebt_stat":"Não enviado"}]}`

Code:
`const csvFromArrayOfObjects = await convertArrayToCSV(dados.rows, {
              separator: '";"',
            });`

After conversion malformed return:
Malformed return:
`"9031909737079";"2";""Mensalidade EAD"";"M";"Mensalidade";"1909737";"7";"40996";"1";"8403349904";""Lucas Eduardo Sestrem"";""RUA ARTHUR RICARDO WIRTH"";""ESCOLA AGRÍCOLA"";"BLUMENAU";"SC";"89037724";""2019-07-29 00:00:00"";"4";""41,84"";"""";"0";"""";"""";"0";"""";""2019-07-01 00:00:00"";"""";"0";"0";"0";"""";"""";""Não enviado"
9031907358071";"2";""Mensalidade EAD"";"M";"Mensalidade";"1907358";"7";"40996";"1";"10098142909";""Daniela Cordeiro Vale"";""LAGOAO DA CRUZ"";""LAGOA DA CRUZ"";""ANTONIO OLINTO"";"PR";"83980000";""2019-07-29 00:00:00"";"4";""68,95"";"""";"0";"""";"""";"0";"""";""2019-07-01 00:00:00"";"""";"0";"0";"0";"""";"""";""Não enviado"
"`

Explanation:
Observe that the last line and the last column put a break between ""Não enviado"\n", than the happens when the last line and the last column have a `space` between the words. if i replace the words with one with no space, it works.


Desired Csv:
`"9031909737079";"2";""Mensalidade EAD"";"M";"Mensalidade";"1909737";"7";"40996";"1";"8403349904";""Lucas Eduardo Sestrem"";""RUA ARTHUR RICARDO WIRTH"";""ESCOLA AGRÍCOLA"";"BLUMENAU";"SC";"89037724";""2019-07-29 00:00:00"";"4";""41,84"";"""";"0";"""";"""";"0";"""";""2019-07-01 00:00:00"";"""";"0";"0";"0";"""";"""";""Não enviado""
"9031907358071";"2";""Mensalidade EAD"";"M";"Mensalidade";"1907358";"7";"40996";"1";"10098142909";""Daniela Cordeiro Vale"";""LAGOAO DA CRUZ"";""LAGOA DA CRUZ"";""ANTONIO OLINTO"";"PR";"83980000";""2019-07-29 00:00:00"";"4";""68,95"";"""";"0";"""";"""";"0";"""";""2019-07-01 00:00:00"";"""";"0";"0";"0";"""";"""";""Não enviado""`



Hope this helps.

**Comment by aichbauer** [comment]
@romeroleonardoalexandre It helps... I'll take a look at it today... stay tuned...

**Comment by aichbauer** [comment]
@romeroleonardoalexandre I tried it and I think the problem is within here:

```js
const csvFromArrayOfObjects = await convertArrayToCSV(dados.rows, { separator: '";"', });
```

See you tell that the separator has to be `";"` which will always apply `";"` when needed... at the last line there is no need of `";"` so it skipps... since it has a `space` in the word, it replaces the contents of the last cell with `"content content"`, which adds additional `"` around the contents, to be valid csv...

but here is the problem... since you use `"` in your separator (which you should not) it does not close the last element...

so here is what I would do...

```js
const csvFromArrayOfObjects = convertArrayToCSV(dados.rows, { separator: ';' });
```

Please try this, and tell me if it is going to work for you, otherwise we have to take a closer look into that problem...

**Comment by romeroleonardoalexandre** [comment]
I place this `";"` because some columns comes with a special char and breaks my CSV, so the solution was to use this way, and in this case, it causes another problem so.
Thanks for the help.
