### ISSUE TITLE
Some double quotes aren't necessary

### ISSUE THREAD

**Issue by bokub** [aichbauer/node-convert-array-to-csv#22]
In the following example :

```js
convertArrayToCSV([['Hello', 'Hello, world', 'Hello world', '', 'Hello']]);
// => Hello,"Hello, world","Hello world","",Hello
```
The double quotes are necessary on the 2nd column because of the comma, but **they are not needed** on the third and fourth ones.

Expected result : 
```js
convertArrayToCSV([['Hello', 'Hello, world', 'Hello world', '', 'Hello']]);
// => Hello,"Hello, world",Hello world,,Hello
```

**Comment by bokub** [comment]
https://github.com/aichbauer/node-convert-array-to-csv/blob/864995494890d499881c03bfb70c72dbf8b9c1c0/src/helpers/check-special-chars-and-empty.js#L5-L15

Inside of checking for special chars such a "," or ".", shouldn't you check if the separator is included in the string ?

In the following example, I want to use a pipe separator, but my second column isn't between double quotes, which will be interpreted as 3 columns instead of 2
```js
convertArrayToCSV([['Hello', 'Hello|world']], {separator: '|'});
// => Hello|Hello|world
```

**Comment by vanodevium** [comment]
@aichbauer Why you use next list of symbols?
```
/[\n\t,;."'`´ ]/
```
Is it editors specified or any other reason?

**Comment by aichbauer** [comment]
@webdevium The official standard mentions:

>    5.  Each field may or may not be enclosed in double quotes (however
>        some programs, such as Microsoft Excel, do not use double quotes
>        at all).  If fields are not enclosed with double quotes, then
>        double quotes may not appear inside the fields.  For example:
> 
>        "aaa","bbb","ccc" CRLF
>        zzz,yyy,xxx
> 
>    6.  Fields containing line breaks (CRLF), double quotes, and commas
>        should be enclosed in double-quotes.  For example:
> 
>        "aaa","b CRLF
>        bb","ccc" CRLF
>        zzz,yyy,xxx

Which means not @bokub is right. We should follow the official standard https://tools.ietf.org/html/rfc4180

What we have to take care of is that we include the current selected separator as @bokub mentioned in the comment.

I am open for every contribution. So if you want to take care of this issue, you would help me a lot.

**Comment by vanodevium** [comment]
@aichbauer Information accepted. I'll help with pleasure!

**Comment by aichbauer** [comment]
@webdevium Great, thank you 😃 

Also, this change would be a major change. Not because it changes the public API in a way in would be used, but the result of the function will be different. And this could break current projects with this implementation. So we should have a closer look at the standard and see if we could make more fixes (which might be breaking) so that we do not have to increment the version number multiple times.
