### ISSUE TITLE
Adding space as a special character (?)

### ISSUE THREAD

**Issue by incadenza** [aichbauer/node-convert-array-to-csv#7]
First off, thanks for the library - it's exactly what I need.

It turns out Pages (the Apple Excel) is struggling to correctly parse csv headers with spaces, for example:
```const headers = ['Last Name', 'Created At'];```

Wrapping these headers with quotes does the job, but I'm having trouble getting the library to do that for me.

It looks like you wrap headers in quotes in the case of special characters. I wanted to run the idea of adding spaces to the list of special characters to wrap?

I'd be happy to contribute a PR if you think this makes sense.

**Comment by aichbauer** [comment]
Hey @incadenza,

thanks for your contribution 👍

The case you mentioned should be handled from this library. 

I am always open for help and would be grateful for a PR to improve this library.

@incadenza do you know if Microsoft Excel imports csv with double quotes in it right? 

in the official standard the say:

>   5.  Each field may or may not be enclosed in double quotes (however
>       some programs, such as Microsoft Excel, do not use double quotes
>      at all).  If fields are not enclosed with double quotes, then
>       double quotes may not appear inside the fields.  For example:
>
>       "aaa","bbb","ccc" CRLF
>       zzz,yyy,xxx

It is from 2005 so I don't know if that is a problem. Maybe we should check for general support of double quotes and then decide for something link `microsoft: true`?

// edit-1: add question about microsoft excel

**Comment by incadenza** [comment]
Ah, good question. On the latest Excel, it seems Excel handles headers perfectly well with or without quotes. So the header "First Name" and First Name both work correctly. It's looking like Libre Office flexible about it as well.

It seems like Numbers is the only one that struggles with headers without quotes so far, which is perhaps not very surprising.

**Comment by aichbauer** [comment]
Thanks for the check. That is great. I think we should always add double quotes when there is a space in an entry or a headerEntry. So we are safe by just adding a space to the special characters I guess.

**Comment by aichbauer** [comment]
@incadenza any update on this issue? Would be helpful if you can make a PR.

**Comment by incadenza** [comment]
@aichbauer apologies for the delay! It's been a busy week here. I should be able to get this in by the end of the week.
