### ISSUE TITLE
Fix: double quotes appearing inside double quotes 

### ISSUE THREAD

**Issue by aichbauer** [aichbauer/node-convert-array-to-csv#9]
As of the official [RFC 4180 Standard for csv](https://tools.ietf.org/html/rfc4180)

>   7.  If double-quotes are used to enclose fields, then a double-quote
>      appearing inside a field must be escaped by preceding it with
>       another double quote.  For example:
>
>       "aaa","b""bb","ccc"

This edge case should be handled by this library.

// edit-1: add link

**Comment by fayanow** [comment]
There seems to be an issue with this recent push.

`/node_modules/convert-array-to-csv/lib/helpers/append-element.js:15
      var thisElement = element.replace('"', '""');
                                ^

    TypeError: element.replace is not a function`

**Comment by aichbauer** [comment]
@garyh6 Would you mind open up a new issue? Could you provide an example? Whats the input, and what is the expected output?

**Comment by aichbauer** [comment]
@garyh6  fixed with #15
